CREATE DATABASE BIADB;

USE BIADB;

CREATE TABLE STUDENT(
STUDENTID int,
LASTNAME VARCHAR(255),
FIRSTNAME VARCHAR(255),
ADDRESS VARCHAR(255),
CITY VARCHAR(255)
);

INSERT INTO STUDENT (STUDENTID, LASTNAME, FIRSTNAME, ADDRESS, CITY)
VALUES (1,'NAKTE','KAMINI','PAREL','MUMBAI');

SELECT * FROM STUDENT;

INSERT INTO STUDENT VALUES(2,'SIDHIQUE','IQRA','BYCULLA','MUMBAI');
INSERT INTO STUDENT VALUES(3,'MORE','ASHUTOSH','KALYAN','KALYAN');
INSERT INTO STUDENT VALUES(4,'GAIKWAD','MANTHAN','CHARNIROAD','SOUTHMUMBAI');
INSERT INTO STUDENT VALUES(5,'MOHITE','VINIT','ANDHERI','MUMBAI');
INSERT INTO STUDENT VALUES(6,'SMI','SAMUEL','ANDHERI');
 
 
 SELECT LASTNAME FROM STUDENT;
 
 ALTER TABLE STUDENT ADD AGE INT;
 
 CREATE TABLE PERSONS (
 PERSONID INT NOT NULL,
 LASTNAME VARCHAR(255) NOT NULL,
 FIRSTNAME VARCHAR(255),
 AGE INT,
 UNIQUE (PERSONID)
 );
 
 INSERT INTO PERSONS VALUE (1,'GAIKWAD','MANTHAN',22);
 SELECT * FROM PERSONS;
 
 SELECT * FROM STUDENT;
 SELECT DISTINCT LASTNAME FROM STUDENT;
 SELECT DISTINCT FIRSTNAME FROM STUDENT;
 
 SELECT * FROM STUDENT;
 
 UPDATE STUDENT
 SET AGE='22' WHERE LASTNAME='MOHITE';
 
  UPDATE STUDENT
 SET AGE='22' WHERE STUDENTID='1';
 
 UPDATE STUDENT
 SET AGE='23' WHERE STUDENTID='2';
 
 UPDATE STUDENT
 SET AGE='21' WHERE STUDENTID='3';
 
UPDATE STUDENT
SET AGE='23' WHERE STUDENTID='4';

SELECT * FROM STUDENT 
WHERE AGE BETWEEN 23 AND 25;

SELECT * FROM STUDENT 
WHERE AGE=21;

SELECT * FROM STUDENT 
WHERE LASTNAME LIKE 'M%';

SELECT * FROM STUDENT 
WHERE CITY IN ('KALYAN','SOUTHMUMBAI');

SELECT * FROM STUDENT;

SELECT AGE, FIRSTNAME FROM STUDENT
WHERE AGE=23 AND FIRSTNAME='IQRA';

SELECT * FROM STUDENT
ORDER BY FIRSTNAME;

SELECT * FROM STUDENT
ORDER BY AGE DESC;


use biadb;
select * from persons;

create table orders(
orderID int not null,
ordernumber int not null,
PERSONID int,
primary key (orderID),
foreign key(PERSONID) references persons(PERSONID)
);

INSERT INTO orders values(1,101,1);
insert into orders values(2,102,1);
insert into orders values(3,301,3);

INSERT INTO PERSONS VALUE (2,'NAKTE','KAMINI',23);
INSERT INTO PERSONS VALUE (3,'SAWANT','VIDDHI',24);
SELECT * FROM PERSONS;
SELECT * FROM ORDERS;

SELECT MIN(AGE) AS minimum_age FROM PERSONS;

SELECT MAX(AGE) AS maximum_age FROM PERSONS;

SELECT COUNT(AGE) AS count_age FROM PERSONS;

SELECT avg(AGE) AS average_age FROM PERSONS;

SELECT sum(AGE) AS sum_age FROM PERSONS;

select * from persons where FIRSTNAME LIKE '%I';

select * from persons where FIRSTNAME LIKE 'K%';

select * from persons where FIRSTNAME LIKE '%AM%';

select * from persons where LASTNAME LIKE '%S%T';
select FIRSTNAME from persons where LASTNAME LIKE '%S%T';


SELECT * FROM PERSONS
inner join orders
on PERSONS.PERSONID = orders.PERSONID;

SELECT * FROM PERSONS
LEFT join orders
on PERSONS.PERSONID = orders.PERSONID;

SELECT * FROM PERSONS
LEFT join orders
on PERSONS.PERSONID = orders.PERSONID
WHERE ORDERS.PERSONID IS NULL;

SELECT * FROM PERSONS
RIGHT join orders
on PERSONS.PERSONID = orders.PERSONID;

SELECT * FROM PERSONS
RIGHT join orders
on PERSONS.PERSONID = orders.PERSONID
WHERE PERSONS.PERSONID IS NULL;

SELECT * FROM PERSONS 
cross JOIN orders;

SELECT * FROM STUDENT;
SELECT count(STUDENTID),CITY
FROM STUDENT
GROUP BY CITY;

SELECT count(STUDENTID),CITY,AGE
FROM STUDENT
GROUP BY AGE;

SELECT * FROM STUDENT;
SELECT count(STUDENTID),CITY
FROM STUDENT
GROUP BY CITY
HAVING COUNT(STUDENTID)>3;


SELECT count(STUDENTID),CITY
FROM STUDENT
GROUP BY CITY
HAVING COUNT(STUDENTID)>=1;

SELECT * FROM salaries